# Generated by AIDA codegen — deterministic EDA script
import os
import json
import numpy as np
import pandas as pd

try:
    import plotly.express as px
except Exception as _e:  # noqa: N816
    px = None


def get_env(name: str, default: str | None = None) -> str:
    value = os.environ.get(name, default)
    if value is None:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def main() -> None:
    # Deterministic seeds
    np.random.seed(42)

    input_path = get_env("AIDA_INPUT")
    output_dir = Path(get_env("AIDA_OUTPUT", "artifacts")).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load data (assumes CSV input by default)
    suffix = Path(input_path).suffix.lower()
    if suffix in (".parquet", ".pq"):
        df = pd.read_parquet(input_path)
    elif suffix in (".jsonl", ".ndjson"):
        df = pd.read_json(input_path, lines=True)
    elif suffix == ".json":
        df = pd.read_json(input_path)
    else:
        df = pd.read_csv(input_path)

    # Basic describe
    describe_html = df.describe(include="all").to_frame().to_html()
    (output_dir / "report.html").write_text(describe_html, encoding="utf-8")

    # First numeric column histogram
    numeric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
    if px is not None and numeric_cols:
        fig = px.histogram(df, x=numeric_cols[0], nbins=30, title=f"Distribution of {numeric_cols[0]}")
        fig.write_html(str(output_dir / f"hist_{numeric_cols[0]}.html"))

    # Emit manifest for artifacts
    artifacts = []
    if (output_dir / "report.html").exists():
        artifacts.append({
            "type": "html",
            "path": str(output_dir / "report.html"),
            "title": "Report",
        })
    if numeric_cols and (output_dir / f"hist_{numeric_cols[0]}.html").exists():
        artifacts.append({
            "type": "html",
            "path": str(output_dir / f"hist_{numeric_cols[0]}.html"),
            "title": f"Distribution of {numeric_cols[0]}",
        })
    print(json.dumps({"artifacts": artifacts}))


if __name__ == "__main__":
    from pathlib import Path
    main()
