from __future__ import annotations

import os
import time
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

try:
    from openai import OpenAI  # type: ignore
except Exception:  # pragma: no cover
    OpenAI = None  # type: ignore


# NOTE: SCRIPT_HEADER removed - no hardcoded fallbacks
# All analysis scripts must be generated by AI based on actual data inspection
# to ensure genuine insights from random data sources


def generate_script(
    inspect_payload: dict,
    prefs: dict | None,
    out_dir: str | os.PathLike[str] = "scripts",
) -> dict:
    ts = int(time.time())
    out_dir_path = Path(out_dir).resolve()
    out_dir_path.mkdir(parents=True, exist_ok=True)
    script_path = out_dir_path / f"analysis_{ts}.py"

    # Generate script using OpenAI - no fallback to static template
    script_text: str | None = _try_generate_with_openai(inspect_payload, prefs)
    
    if script_text is None:
        raise RuntimeError(
            "Failed to generate analysis script. Please ensure:\n"
            "1. AIDA_MODEL_PROVIDER is set to 'openai' (or unset for default)\n"
            "2. OPENAI_API_KEY is configured in your environment\n"
            "3. The OpenAI API is accessible\n"
            "4. Install openai package: pip install openai\n\n"
            "No hardcoded fallback template is used to ensure genuine data insights."
        )
    
    script_path.write_text(script_text, encoding="utf-8")
    return {"scriptPath": str(script_path), "scriptText": script_text}


def _try_generate_with_openai(
    inspect_payload: dict, prefs: Optional[dict]
) -> Optional[str]:
    """
    Generate analysis script using OpenAI API.
    Returns None if configuration is missing or generation fails.
    Caller should handle None by raising appropriate error.
    """
    load_dotenv()
    provider = os.environ.get("AIDA_MODEL_PROVIDER", "openai").lower()
    model = os.environ.get("AIDA_MODEL", "gpt-4o-mini")
    api_key = os.environ.get("OPENAI_API_KEY")
    
    # Check prerequisites
    if provider != "openai":
        return None
    
    if not api_key:
        return None
    
    if OpenAI is None:
        return None

    # Compose messages using prompt_composer
    try:
        from .prompt_composer import AnalysisPrefs, build_messages  # local import
    except Exception:
        return None

    prefs_obj = AnalysisPrefs(
        viz=(prefs or {}).get("viz", "plotly"),
        engine=(prefs or {}).get("engine", "pandas"),
        max_charts=(prefs or {}).get("max_charts", 8),
        category_top_n=(prefs or {}).get("category_top_n", 30),
        pairplot_max_numeric=(prefs or {}).get("pairplot_max_numeric", 6),
        correlation_min_numeric=(prefs or {}).get("correlation_min_numeric", 3),
        missingness_threshold=(prefs or {}).get("missingness_threshold", 0.05),
        prefer_interactive=(prefs or {}).get("prefer_interactive", True),
        target=(prefs or {}).get("target"),
        time_col=(prefs or {}).get("time_col"),
    )
    messages = build_messages(inspect_payload or {}, prefs_obj)

    try:
        client = OpenAI(api_key=api_key)
        resp = client.chat.completions.create(
            model=model,
            messages=[{"role": m["role"], "content": m["content"]} for m in messages],
            temperature=0.1,
            max_tokens=4000,
        )
        content = resp.choices[0].message.content or ""
        # Strip code fences if any
        content = content.strip()
        if content.startswith("```"):
            content = content.strip("`\n")
            # Remove possible language hint line
            if "\n" in content:
                first_line, rest = content.split("\n", 1)
                if first_line.strip().isalpha():
                    content = rest
        return content
    except Exception:
        # Return None so caller can provide detailed error
        return None
