from __future__ import annotations

import os
import time
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

try:
    from openai import OpenAI  # type: ignore
except Exception:  # pragma: no cover
    OpenAI = None  # type: ignore


SCRIPT_HEADER = """
# Generated by AIDA codegen — deterministic EDA script
import os
import json
from pathlib import Path
import numpy as np
import pandas as pd

try:
    import plotly.express as px
except Exception as _e:  # noqa: N816
    px = None


def get_env(name: str, default: str | None = None) -> str:
    value = os.environ.get(name, default)
    if value is None:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def main() -> None:
    # Deterministic seeds
    np.random.seed(42)

    input_path = get_env("AIDA_INPUT")
    output_dir = Path(get_env("AIDA_OUTPUT", "artifacts")).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load data (assumes CSV input by default)
    suffix = Path(input_path).suffix.lower()
    if suffix in (".parquet", ".pq"):
        df = pd.read_parquet(input_path)
    elif suffix in (".jsonl", ".ndjson"):
        df = pd.read_json(input_path, lines=True)
    elif suffix == ".json":
        df = pd.read_json(input_path)
    else:
        df = pd.read_csv(input_path)

    # Basic describe
    describe_html = df.describe(include="all").to_html()
    (output_dir / "report.html").write_text(describe_html, encoding="utf-8")

    # First numeric column histogram
    numeric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
    if px is not None and numeric_cols:
        fig = px.histogram(df, x=numeric_cols[0], nbins=30, title=f"Distribution of {numeric_cols[0]}")
        fig.write_html(str(output_dir / f"hist_{numeric_cols[0]}.html"))

    # Emit manifest for artifacts
    artifacts = []
    if (output_dir / "report.html").exists():
        artifacts.append({
            "type": "html",
            "path": str(output_dir / "report.html"),
            "title": "Report",
        })
    if numeric_cols and (output_dir / f"hist_{numeric_cols[0]}.html").exists():
        artifacts.append({
            "type": "html",
            "path": str(output_dir / f"hist_{numeric_cols[0]}.html"),
            "title": f"Distribution of {numeric_cols[0]}",
        })
    print(json.dumps({"artifacts": artifacts}))


if __name__ == "__main__":
    main()
""".lstrip()


def generate_script(
    inspect_payload: dict,
    prefs: dict | None,
    out_dir: str | os.PathLike[str] = "scripts",
) -> dict:
    ts = int(time.time())
    out_dir_path = Path(out_dir).resolve()
    out_dir_path.mkdir(parents=True, exist_ok=True)
    script_path = out_dir_path / f"analysis_{ts}.py"

    # Generate script using OpenAI - no fallback to static template
    script_text: str | None = _try_generate_with_openai(inspect_payload, prefs)
    
    if script_text is None:
        raise RuntimeError(
            "Failed to generate analysis script. Please ensure:\n"
            "1. AIDA_MODEL_PROVIDER is set to 'openai' (or unset for default)\n"
            "2. OPENAI_API_KEY is configured in your environment\n"
            "3. The OpenAI API is accessible\n"
            "4. Install openai package: pip install openai\n\n"
            "No hardcoded fallback template is used to ensure genuine data insights."
        )
    
    script_path.write_text(script_text, encoding="utf-8")
    return {"scriptPath": str(script_path), "scriptText": script_text}


def _try_generate_with_openai(
    inspect_payload: dict, prefs: Optional[dict]
) -> Optional[str]:
    load_dotenv()
    provider = os.environ.get("AIDA_MODEL_PROVIDER", "openai").lower()
    model = os.environ.get("AIDA_MODEL", "gpt-4o-mini")
    api_key = os.environ.get("OPENAI_API_KEY")
    if provider != "openai" or not api_key or OpenAI is None:
        return None

    # Compose messages using prompt_composer
    try:
        from .prompt_composer import AnalysisPrefs, build_messages  # local import
    except Exception:
        return None

    prefs_obj = AnalysisPrefs(
        viz=(prefs or {}).get("viz", "plotly"),
        engine=(prefs or {}).get("engine", "pandas"),
    )
    messages = build_messages(inspect_payload or {}, prefs_obj)

    try:
        client = OpenAI(api_key=api_key)
        resp = client.chat.completions.create(
            model=model,
            messages=[{"role": m["role"], "content": m["content"]} for m in messages],
            temperature=0.1,
            max_tokens=4000,
        )
        content = resp.choices[0].message.content or ""
        # Strip code fences if any
        content = content.strip()
        if content.startswith("```"):
            content = content.strip("`\n")
            # Remove possible language hint line
            if "\n" in content:
                first_line, rest = content.split("\n", 1)
                if first_line.strip().isalpha():
                    content = rest
        return content
    except Exception:
        return None
